---
# tasks file for ansible-role-tripleo-overcloud-scale-nodes

# TODO: 1. Abstract type of node to be scaled
# TODO: 2. Add overcloud validation post scale
# TODO: 3. Add 'remove node' post validation
# TODO: 4. Add overcloud validation post 'remove node'

- name: Determine initial number of node(s) that will be scaled
  shell: >
    source "{{ artosn_working_dir }}/stackrc";
    nova list | grep "{{ node_to_scale }}" | cut -f2- -d':' | wc -l
  register: initial_node_count

- name: Copy scale deployment template to undercloud
  template:
    src: scale-deployment.j2
    dest: "{{ artosn_working_dir }}/scale-deployment.sh"
    mode: 0755

- name: Call scale deployment script
  shell: >
    source "{{ artosn_working_dir }}/stackrc";
    "{{ artosn_working_dir }}"/scale-deployment.sh &> overcloud_deployment_scale_console.log;

- name: Poll heat stack-list to determine when complete
  shell: >
    source "{{ artosn_working_dir }}"/stackrc;
    heat stack-list
  register: heat_stack_list_result
  until: heat_stack_list_result.stdout.find("COMPLETE") != -1
  retries: 10
  delay: 180

- name: Determine the post scale node count
  shell: >
    source "{{ artosn_working_dir }}/stackrc";
    nova list | grep "{{ node_to_scale }}" | cut -f2- -d':' | wc -l
  register: post_scale_node_count

- name: Check that post scale node count is correct
  fail: msg="Overcloud nova list does not show expected number of {{ node_to_scale }} services"
  when: post_scale_node_count.stdout != "{{ final_scale_value }}"
