---
# tasks file for ansible-role-tripleo-overcloud-scale-nodes

- include: pre-scale.yml
  when: artosn_scale_nodes
  tags:
    - pre-overcloud-scale-nodes

- include: scale-nodes.yml
  when: artosn_scale_nodes
  tags:
    - overcloud-scale-nodes

# Optionally reduce scale back to original state
- include: undo-scale.yml
  when: artosn_undo_scale
  tags:
    - post-overcloud-scale-nodes-delete
