---
# tasks file for ansible-role-tripleo-overcloud-scale-nodes

- include: pre-scale.yml
  when: artosn_scale_nodes|bool
  tags:
    - pre-overcloud-scale-nodes

- include: scale-nodes.yml
  when: artosn_scale_nodes|bool
  tags:
    - overcloud-scale-nodes

# Optionally delete the original node of type scaled
- include: delete-original-node.yml
  when: artosn_delete_original_node|bool
  tags:
    - post-overcloud-scale-nodes-delete
