---

# Prep for scale
- name: Determine initial number of node(s) that will be scaled
  shell: >
    source "{{ artosn_working_dir }}/stackrc";
    nova list | grep "{{ node_to_scale }}" | cut -f2- -d':' | wc -l
  register: initial_node_count

- name: Register pre-scale nova list
  shell: >
    source "{{ artosn_working_dir }}/stackrc";
    nova list
  register: pre_scale_nova_list

- debug: msg={{ pre_scale_nova_list.stdout_lines }}
  when: pre_scale_nova_list is defined

- name: Copy scale deployment template to undercloud
  template:
    src: scale-deployment.j2
    dest: "{{ artosn_working_dir }}/scale-deployment.sh"
    mode: 0755
