---

# Scale nodes w/o delete
- name: Scale overcloud nodes
  hosts: undercloud
  roles:
    - { role: ansible-role-tripleo-overcloud-scale-nodes, artosn_scale_nodes: true, artosn_delete_original_node: false }

# Delete the original node of type that was scaled - ensure overcloud validates after reducing scale
- name: Delete original node of type scaled
  hosts: undercloud
  roles:
    - { role: ansible-role-tripleo-overcloud-scale-nodes, artosn_scale_nodes: false, artosn_delete_original_node: true }

# NOTE(hrybacki: inventory regeneration and overcloud validation must be completed in a second playbook. The
# deleted node is removed from the hosts file. However, it still exists in memory and will cause the
# 'ansible-role-tripleo-inventory: regenerate ssh config' task to fail when attempting to acces non-existant host vars
