---

control_memory: 16384
control_vcpu: 4

overcloud_nodes:
  - name: control_0
    flavor: control

  - name: compute_0
    flavor: compute

  - name: compute_1
    flavor: compute

run_tempest: false
tempest_config: false
test_ping: true
enable_pacemaker: true
network_isolation: true
deploy_timeout: 60

# General deployment info
libvirt_args: "--libvirt-type qemu"

flavor_args: >-
  --control-flavor {{flavor_map.control
  if flavor_map is defined and 'control' in flavor_map else 'oooq_control'}}
  --compute-flavor {{flavor_map.compute
  if flavor_map is defined and 'compute' in flavor_map else 'oooq_compute'}}

timeout_args: "--timeout {{ deploy_timeout }}"

extra_args: "--compute-scale 1 --neutron-network-type vxlan --neutron-tunnel-types vxlan -e {{ artosn_overcloud_templates_path }}/environments/network-isolation.yaml -e {{ artosn_overcloud_templates_path }}/environments/net-single-nic-with-vlans.yaml -e ~/network-environment.yaml --ntp-server pool.ntp.org"

# Pulled this out so we can hand these configs to the openstack overcloud node delete command
scale_extra_configs: "-e {{ artosn_overcloud_templates_path }}/environments/network-isolation.yaml -e {{ artosn_overcloud_templates_path }}/environments/net-single-nic-with-vlans.yaml -e /home/stack/network-environment.yaml"
scale_extra_args: "--{{ node_to_scale }}-scale {{ final_scale_value }} --neutron-network-type vxlan --neutron-tunnel-types vxlan {{ scale_extra_configs }} --ntp-server pool.ntp.org"


# Scale deployment info
node_to_scale: compute # Type of node to scale
initial_scale_value: 1 # Initial number of nodes to deploy
final_scale_value: 2   # Number of additional nodes to add during the scale

# Scale deployment arguments
scale_args: >-
  {{ libvirt_args }}
  {{ flavor_args }}
  {{ timeout_args }}
  {{ pacemaker_args }}
  {{ scale_extra_args }}

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - scale-deployment
    - delete-node
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - scale-deployment
    - delete-node
    - overcloud-validate

# Path to tripleo-heat-templates
artosn_overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates

# Sample call
# ./deploy.sh -v --playbook scale_nodes --config-file config/scale/scale_compute.yml
